
import type { Metadata } from "next";
import { Urbanist } from 'next/font/google'

const urbanist = Urbanist({ subsets: ["latin"], variable: '--font-display' })


import "./globals.css";
import Header from "./components/Header";
import { ThemeProvider } from "./components/theme-provider";
import Container from "./components/Container";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={urbanist.className}>

        <Header />
          {children}
          <Footer />
      </body>
    </html>
  );
}
