import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import { IBM_Plex_Mono } from "next/font/google";

import { Toaster } from "@/app/components/ui/toaster";
const urbanist = Urbanist({ subsets: ["latin"], variable: "--font-display" });
const ibmPlexMono = IBM_Plex_Mono({
  subsets: ["cyrillic"],
  weight: "500",
  variable: "--font-display",
});

import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${urbanist.variable} ${ibmPlexMono.variable}`}>
        <Toaster />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
